- .github/workflows/build-test-staging.yml
- .github/workflows/unit-test.yml
- .github/workflows/webpack-diff.yml
Because
- Action still use yarn
This commit
- Update action to use pnpm
> feat: update action for pnpm

- .github/workflows/build-test-staging.yml
- .github/workflows/unit-test.yml
Because
- Pnpm is not native supported by github action
This commit
- Add pnpm at github action
> feat: setup pnpm at github action

- .github/workflows/build-test-staging.yml
- .github/workflows/webpack-diff.yml
Because
- Deploy action can not correctly operate
This commit
- Replace yarn install with pnpm install
- Replace Vault secrets with Github Action secrets
> fix: fix action deploy issue

- src/components/docs/DocsFooter.tsx
- src/components/docs/DocsLayout/index.tsx
- src/components/docs/index.ts
- src/pages/docs/concepts/vdp.mdx
- src/styles/docsBaseStyle.ts
- tailwind.config.js
Because
- Old typography style is hard to read
This commit
- Update typography style
- Fix sidebar top offset's style is not correct issue
> feat: update tailwind typography style

- next.config.mjs
- package.json
- pnpm-lock.yaml
- src/components/docs/DocsLayout/index.tsx
- src/pages/_app.tsx
- src/styles/slack-dark.json
Because
- We need code syntax highlighting
This commit
- Implement code-hike
> feat: Implement code hike

- src/components/docs/DocsLayout.tsx
- src/components/docs/LeftSidebar/Section.tsx
- src/components/docs/LeftSidebar/index.tsx
- src/components/docs/Nav/Nav.tsx
- src/components/docs/RightSidebar.tsx
- src/pages/docs/index.tsx
Because
- The style of documentation have minor issues
This commit
- Fix LeftSidebar container not expand to full height issue
- Fix empty page will make page collapse issue
- close #154
> fix: fix various style issues

- next-sitemap.config.js
- package.json
- pnpm-lock.yaml
- public/robots.txt
- public/sitemap-0.xml
- public/sitemap.xml
Because
- We need to generate sitemap
This commit
- Add next-sitemap to generate sitemap
> feat: add next-sitemap to generate sitemap

- src/components/docs/DocsLayout.tsx
- src/components/docs/RightSidebar.tsx
Because
- RightSidebar is not sticky
This commit
- Fix right sidebar not sticky issue
> fix: fix right sidebar not sticky issue

- next.config.mjs
- package.json
- pnpm-lock.yaml
- tailwind.config.js
Because
- Heading need autolink to itself
This commit
- Add rehype-autolink-headings
- Implement autolink heading style
> feat(docs): add autolink heading

- src/components/docs/DocsLayout.tsx
- src/components/docs/RightSidebar/ContributeLinks.tsx
- src/components/docs/RightSidebar/RightSidebar.tsx
- src/components/docs/RightSidebar/TableOfContent.tsx
- src/components/docs/RightSidebar/index.ts
Because
- We need "Edit this page" on document
This commit
- Add edit this page on docs RightSidebar
> feat: add edit this page on docs RightSidebar

- src/lib/color-json/index.stories.tsx
- src/lib/color-json/index.tsx
Because
- To make color-json better
This commit
- Refactor the function name of color-json lib
> refactor: refactor the function name of color-json lib

- next.config.mjs
- package.json
- pnpm-lock.yaml
- src/components/docs/DocsLayout.tsx
- src/styles/global.css
Because
- We want our header anchor to act like vitepress
This commit
- Refactor header anchor
> refactor: refactor header anchor

- src/components/docs/ArticleNavigationButton.tsx
- src/components/docs/DocsLayout.tsx
- src/components/docs/LeftSidebar/Section.tsx
- src/types/docs.ts
Because
- #199
This commit
- Support prev/next article navigation button
- close #199
> feat: support prev/next article navigation button

- src/components/docs/DocsLayout.tsx
- src/components/docs/RightSidebar/TableOfContent.tsx
Because
- #203
This commit
- Temporarily disable smooth scroll behavior
> fix: disable smooth scroll behavior

- docs.config.tsx
- src/pages/docs/core-concepts/connector.mdx
- src/pages/docs/core-concepts/model.mdx
- src/pages/docs/core-concepts/overview.mdx
- src/pages/docs/destination-connectors/overview.mdx
- src/pages/docs/import-models/artivc.mdx
- src/pages/docs/import-models/github.mdx
- src/pages/docs/prepare-models/model-card.mdx
- src/pages/docs/prepare-models/overview.mdx
- src/pages/docs/start-here/configuration.mdx
- src/pages/docs/start-here/faq.mdx
- src/pages/docs/start-here/getting-started.mdx
- src/pages/docs/start-here/roadmap.mdx
- src/pages/docs/tutorials/build-a-sync-cls-pipeline.mdx
- src/pages/docs/tutorials/build-an-async-det-pipeline.mdx
Because
- some links are broken
This commit
- fix broken links
> docs: fix broken links

- docs.config.tsx
- src/components/docs/Nav/Nav.tsx
- src/components/docs/Nav/SubNav.tsx
Because
- #208
This commit
- close #208
> feat: shrink the size of vdp logo at mobile view and fix sub-navbar not align issue

- src/components/docs/DocsLayout.tsx
Because
- We want to prompt the contribution done by every contributor.
This commit
- Add contributor's name in last-updated info.
> feat: add contributor's name in last-updated info

- src/pages/docs/start-here/faq.mdx
- src/pages/docs/start-here/roadmap.mdx
Because
- improve documentation
This commit
- fix typos
- close #215
> docs(start-here): tinker little stuff

- .github/workflows/check-main-lighthouse-score.yml
- .github/workflows/deploy-prod.yml
Because
- #211
This commit
- close #211
> fix: fix lighthouse action not correctly make tmp/artifacts folder

- src/components/docs/DocsLayout.tsx
Because
- We want to include the author's GitHub link in the last edited info
This commit
- Update last-edited info to include author GitHub URL
> feat: update last-edited info to include authou github url

- src/components/docs/DocsLayout.tsx
- src/components/docs/LeftSidebar/Section.tsx
- src/components/docs/index.ts
- src/pages/docs/[...path].tsx
Because
- #238 
- #193 
This commit
- Fix sidebar reset position issue (close #193)
- Implement round image (close #238)
> fix: fix sidebar reset position issue and implement round image

- README.md
Because
- we would like to make `README.md` layout identical across different repositories
This commit
- refines the `README.md` layout
> chore: improve README.md

- docs/core-concepts/cv-task.mdx
Because
- we're iterating the documentation
This commit
- update the cv task format
> docs: update future cv task protocol

- docs/core-concepts/cv-task.mdx
- docs/core-concepts/pipeline.mdx
- docs/development/setup-local-development.mdx
- docs/start-here/configuration.mdx
- docs/start-here/roadmap.mdx
- docs/tutorials/build-a-sync-cls-pipeline.mdx
- docs/tutorials/build-an-async-det-pipeline.mdx
Because
- headers are not ordered in an incremental way 
This commit
- update page headers
> docs(core-concepts,start-here,tutorials,development): update headers

- README.md
- src/components/docs/LeftSidebar/Section.tsx
- src/styles/docs.css
- tailwind.config.js
Because
- #245
- #246
This commit
- Implement toggle block (close #245)
- refactor left sidebar arrow direction (#close #246)
> feat: Implement toggle box

- src/pages/newsletter.tsx
- src/styles/docs.css
Because
- #251
- #253 
This commit
- fix the newsletter archive's order issue (close #251)
- fix the selection color of codegroup (close #253)
> fix: fix newsletter archive's order issue

- .eslintrc.json
- src/components/ui/AnnouncementBar/AnnouncementBar.tsx
- src/components/ui/AnnouncementBar/announcementBar.spec.tsx
- src/components/ui/Nav/Nav.tsx
Because
- We have new banner 
This commit
- Update product website banner
> feat: update product website banner

- docs/core-concepts/cv-task.mdx
- docs/start-here/faq.mdx
Because
- maintaining documentation
This commit
- update FAQ
- fix a typo in other doc page
> docs(start-here): update faq

- src/styles/global.css
Because
-  Sep newsletter has a customized block that causes the archive has a style issue
This commit
- Fix sep nesletter style issue
> fix: fix sep nesletter style issue

- src/components/about/OurMembers/MemberKernelSvg.tsx
- src/components/career/CareerPositionDetailsSection/PositionDescription.tsx
- src/components/career/CareerPositionDetailsSection/PositionInfo.tsx
- src/components/ui/AnnouncementBar/AnnouncementBar.tsx
- src/components/ui/AnnouncementBar/index.ts
- src/components/ui/ContentContainer.tsx
- src/components/ui/PageBase.tsx
- src/components/ui/index.ts
- src/contexts/AnnouncementBarContext.tsx
- src/lib/github/index.ts
- src/pages/_document.tsx
- src/pages/docs/[...path].tsx
Because
- #145
This commit
- Deprecate React FC type (close #145)
> chore: deprecate React FC type

- docs/tutorials/build-a-sync-cls-pipeline.mdx
- docs/tutorials/build-an-async-det-pipeline.mdx
Because
- we need to refactor the documentation 
This commit
- update low code requests
> docs(tutorials): refactor low code

- package.json
- pnpm-lock.yaml
- src/components/landing/Hero/DiscordCta.tsx
- src/components/landing/Hero/GitHubCta.tsx
- src/components/landing/Hero/Headline.tsx
- src/components/landing/Hero/Hero.tsx
- src/components/landing/Hero/SubHeadline.tsx
- src/pages/index.tsx
- tailwind.config.js
Because we have a new landing page design (#273). This commit implements the new Hero section
> feat: implement new Hero design

- src/components/ui/Nav/DocsPageLink.tsx
- src/components/ui/Nav/GithubTextLink.tsx
- src/components/ui/Nav/Nav.tsx
Because we have the new product-website design (#273), this commit updates the styles of the nav.
> feat: update nav styles

- src/components/landing/Hero/DiscordCtaButton.tsx
- src/components/landing/Hero/GitHubCtaButton.tsx
- src/components/landing/Hero/Hero.tsx
This commit makes the Hero section responsive and renames the DiscordCta, GitHubCta to DiscordCtaButton and GitHubCtaButton.
> feat: make the Hero section responsive

- src/components/ui/Footer/Footer.tsx
This commit makes the Footer section responsive.
> feat: makes the Footer section responsive

- src/components/landing/Community/Community.tsx
- src/components/landing/Community/CommunityBlock/CommunityBlock.tsx
This commit makes the community section responsive.
> feat: make the community section responsive

- package.json
- pnpm-lock.yaml
- src/components/landing/HowItWorks/HowItWorks.tsx
- src/components/landing/HowItWorks/HowItWorksRow/HowItWorksRow.tsx
- src/components/landing/HowItWorks/IconsCube/IconsCube.tsx
- src/components/landing/NoCodeInterface.tsx
- src/components/landing/Vdp/VdpFlow/VdpFlow.tsx
This commit makes the how it works section responsive and fix the Vdp section's overflow issue.
> feat: make the how it works section responsive

- src/components/landing/CaseStudy/ControlPanel/ControlPanel.tsx
Leverage useMutationObserver to get notified about the container changes and update the line's position. This may lead to an additional deps in the useEffect hook we use to calculate the lineDataset, but unfortunately, this is necessary.
> fix: fix ControlPanel not render correctly issue

- src/components/landing/InstillCloud.tsx
- src/components/ui/SecureYourSpot.tsx
- src/components/ui/StayInTheLoop.tsx
- src/components/ui/SubscribeNewsletterForm.tsx
- src/pages/index.tsx
This commit implements the new InstillCloud design and alters the design of StayInTheLoop and SecureYourSpot section.
> feat: implement new instill cloud section

- src/components/landing/CaseStudy/CaseStudy.tsx
- src/components/landing/CaseStudy/ControlPanel/ControlPanel.tsx
- src/components/landing/CaseStudy/ControlSelectWrapper.tsx
- src/components/landing/Faq/Faq.tsx
- src/components/landing/Faq/FaqText.tsx
- src/components/landing/Vdp/Vdp.tsx
- src/components/landing/Vdp/VdpArrowBlock/VdpArrowBlock.tsx
- src/components/landing/Vdp/VdpFlow/VdpFlow.tsx
- src/components/ui/BlueprintContainer.tsx
- src/pages/index.tsx
This commit implements CaseStudy mobile view. It covers the automated ControlPanel. The custom ControlPanel is still under construction.
> feat: Implement CaseStudy mobile view

- package.json
- pnpm-lock.yaml
- src/components/landing/CaseStudy/AccordionContentLayout/AccordionContentLayout.tsx
- src/components/landing/CaseStudy/CaseStudy.tsx
- src/components/landing/CaseStudy/ControlPanel/ControlPanel.tsx
- src/components/landing/CaseStudy/ControlPanelItem/ControlPanelItem.tsx
- src/components/landing/CaseStudy/ControlSelectWrapper.tsx
- src/components/landing/Faq/Faq.tsx
- src/components/landing/Vdp/VdpFlow/VdpFlow.tsx
- src/components/ui/BlueprintContainer.tsx
- src/hooks/useRefPosition.tsx
This commit uses embla carousel to implement CaseStudy customization section at mobile view.
> feat: Implement case study customization

- docs.config.tsx
- src/components/docs/ArticleNavigationButton.tsx
- src/components/docs/DocsFooter.tsx
- src/components/docs/DocsLayout.tsx
- src/components/docs/LeftSidebar/LeftSidebar.tsx
- src/components/docs/LeftSidebar/Section.tsx
- src/components/docs/LeftSidebar/index.ts
- src/components/docs/Nav/Item.tsx
- src/components/docs/Nav/Nav.tsx
- src/components/docs/Nav/SubNav.tsx
- src/components/docs/Nav/index.ts
- src/components/docs/RightSidebar/ContributeLinks.tsx
- src/components/docs/RightSidebar/RightSidebar.tsx
- src/components/docs/RightSidebar/TableOfContent.tsx
- src/components/docs/RightSidebar/index.ts
- src/components/docs/index.ts
- src/types/docs.ts
This commit replace all default export in component/docs. #314
> feat: deprecate default export in docs folder

- src/components/policy/PolicyPageLayout.tsx
- src/components/ui/Nav/Nav.tsx
This commit updates policy page layout to follow the new design. (#273 ) It also fixes a display bug of announcement bar.
> feat: update policy page

- src/components/policy/PolicyPageLayout.tsx
- src/components/policy/index.ts
- src/components/ui/AnnouncementBar/AnnouncementBar.tsx
- src/components/ui/AnnouncementBar/index.ts
- src/components/ui/BackToPreviousPageLink.tsx
- src/components/ui/BlueprintContainer.tsx
- src/components/ui/ContentContainer.tsx
- src/components/ui/ExploreMoreScrollButton.tsx
- src/components/ui/Footer/Footer.tsx
- src/components/ui/Footer/SocialLinks.tsx
- src/components/ui/Footer/Tab.tsx
- src/components/ui/Footer/index.ts
- src/components/ui/GetEarlyAccessButton.tsx
- src/components/ui/GithubCtaButton.tsx
- src/components/ui/JoinDiscordButton.tsx
- src/components/ui/LearnMoreButton.tsx
- src/components/ui/Nav/DocsPageLink.tsx
- src/components/ui/Nav/GithubTextLink.tsx
- src/components/ui/Nav/Nav.tsx
- src/components/ui/Nav/index.ts
- src/components/ui/PageBase.tsx
- src/components/ui/PageHead.tsx
- src/components/ui/ReactMarkdownWrapper.tsx
- src/components/ui/SecureYourSpot.tsx
- src/components/ui/SimpleHorizontalLine.tsx
- src/components/ui/StayInTheLoop.tsx
- src/components/ui/SubscribeNewsletterForm.tsx
- src/components/ui/index.ts
This commit replace default export with named export (#314) in components/ui folder
> feat: deprecate default export in components/ui

- src/components/career/CareerGeneralIntro.tsx
- src/components/career/index.ts
- src/components/early-access/EarlyAccessHero.tsx
- src/components/early-access/index.ts
- src/components/ui/MailchimpSignupForm.tsx
- src/pages/career/index.tsx
- src/pages/get-access.tsx
This commit update get-early-access page design (#273)
> feat: update early access page

- docs/start-here/roadmap.mdx
Because
- we want to keep the roadmap up-to-date
This commit
- update the roadmap
> docs(start-here): update roadmap

- src/components/about/OurMembers/MemberIntro.tsx
- src/components/landing/CodeShowcase/Terminal/Terminal.tsx
- src/lib/color-json/colorJson.tsx
- src/lib/color-json/index.stories.tsx
Because we have new colorJson lib, this commit deprecate the old member intro.
> feat: deprecate old member intro

- src/components/landing/CaseStudy/CaseStudy.tsx
- src/components/landing/CaseStudy/ShowcaseImage.tsx
This commit fixed various CaseStudy's visual bugs
> fix: fix CaseStudy visual issue

- src/components/landing/CaseStudy/CaseStudy.tsx
This commit fixed typo and visual bugs.
> fix: fix CaseStudy visual bugs

- src/components/landing/CaseStudy/CaseStudy.tsx
This commit fixed CaseStudy wrong icon.
> fix: fix wrong icon

- package.json
- pnpm-lock.yaml
- src/components/landing/CaseStudy/CaseStudy.tsx
- src/components/landing/CaseStudy/ControlPanel/ControlPanel.tsx
- src/components/landing/CaseStudy/ControlPanelItem/ControlPanelItem.stories.tsx
- src/components/landing/CaseStudy/ControlPanelItem/ControlPanelItem.tsx
- src/hooks/useRefPosition.tsx
Because CaseStudy has a bug that will affect how we calculate the position of items, this commit fixes this issue and optimize the component structure.
> fix: optimize case study and fixes calculation issue

- src/components/landing/CodeShowcase/Terminal/Terminal.tsx
This commit fixes CodeShowcase indent
> fix: fix CodeShowcase indent

- src/components/landing/HowItWorks/HowItWorks.tsx
This commit fixes HowItWorks section label text.
> fix: fix HowItWorks section label

- src/components/landing/CaseStudy/AccordionContentLayout/AccordionContentLayout.tsx
- src/components/landing/CaseStudy/CaseStudy.tsx
- src/components/landing/CaseStudy/ShowcaseImage.tsx
- src/components/landing/CaseStudy/ShowcaseTable/ShowcaseTable.tsx
This commit fixes CaseStudy transition issue and optimize the render of this component.
> fix: fix case study transition issue

- src/components/landing/CodeShowcase/AccordionContent.tsx
- src/components/landing/CodeShowcase/CodeShowcase.tsx
- src/components/landing/Community/Community.tsx
- src/components/landing/HowItWorks/HowItWorksRow/HowItWorksRow.tsx
- src/components/landing/InstillCloud.tsx
- src/components/landing/NoCodeInterface.tsx
- src/components/ui/SectionHeader.tsx
This commit fixes SectionHeader margin and refactor CodeShowcase section's order at mobile view.
> refactor: refactor code showcase

- src/components/about/OurCompany.tsx
- src/components/about/OurValue/OurValue.tsx
- src/components/career/PositionDetails/PositionInfoBlock.tsx
- src/components/career/PositionList/CareerPositionListItem.tsx
- src/components/career/PositionList/PositionList.tsx
- src/components/ui/SectionHeader.tsx
This commit fixes word-spacing issue at AboutPage and CareerPage. (close #355)
> fix: fix word spacing at AboutPage and CareerPage

- src/components/ui/Nav/CareerPageLink.tsx
- src/components/ui/Nav/Nav.tsx
- tailwind.config.js
This commit update announcement bar word to show that we are hiring (close #354) and add CraeerPageLink in Navbar.
> feat: update announcement

- package.json
- pnpm-lock.yaml
- src/components/landing/CaseStudy/CaseStudy.tsx
- src/components/landing/CaseStudy/ShowcaseImage.tsx
- src/components/ui/Footer/Tab.tsx
- src/components/ui/ImgWithFallback.tsx
- src/hooks/useAnimationFrameLoop.tsx
- src/hooks/useRefPosition.tsx
- src/pages/about.tsx
- src/pages/index.tsx
This PR updates Footer style and fixes CaseStudy wrong icon (close #363)
> feat: update footer style

- docs.config.tsx
- package.json
- pnpm-lock.yaml
- src/components/docs/Nav/Item.tsx
- src/components/docs/Nav/Nav.tsx
- src/components/docs/Nav/SubNav.tsx
- src/components/ui/PageHead.tsx
- src/pages/_app.tsx
- src/pages/docs/[...path].tsx
- src/styles/docs.css
- src/types/docs.ts
- tailwind.config.js
This commit implement DocSearch and fix several visual issue at doc navbar
> feat: Implement docsearch

- src/components/docs/Nav/Item.tsx
- src/components/docs/Nav/Nav.tsx
- src/styles/docs.css
This commit update Navbar style to make it more fit into our color palette.
> feat: update Navbar style

- src/components/ui/PageBase.tsx
- src/pages/index.tsx
This commit fixes landing page dynamic loading issue (close #371)
> fix: fix landing page dynamic load issue

- src/components/ui/Footer/Footer.tsx
This commit refactors About Instill Ai to About Us at Footer (close #383)
> refactor: refactor About Instill Ai to About Us at Footer

- package.json
- pnpm-lock.yaml
- src/lib/github/index.ts
This commits replaces axios with octokit when request GitHub API.
> feat: replace axios with octokit when request GitHub API

- src/components/ui/Footer/AnimateSlogan.css
- src/components/ui/Footer/AnimateSlogan.tsx
- src/components/ui/Footer/Footer.tsx
- src/pages/_app.tsx
This commit implements footer text animation "WHERE VISUAL DATA PREPARATION MADE FOR ALL"
> feat: impl footer text animation

- README.md
- docs/core-concepts/connector.mdx
- docs/core-concepts/cv-task.mdx
- docs/core-concepts/model.mdx
- docs/core-concepts/overview.mdx
- docs/core-concepts/pipeline.mdx
- docs/import-models/github.mdx
- docs/prepare-models/model-card.mdx
- docs/start-here/faq.mdx
- docs/start-here/getting-started.mdx
- docs/tutorials/build-a-sync-cls-pipeline.mdx
- docs/tutorials/build-an-async-det-pipeline.mdx
- src/components/landing/CaseStudy/ControlPanel/ControlPanel.tsx
- src/components/ui/ZoomableImg.tsx
- src/components/ui/index.ts
- src/lib/markdown/index.ts
- src/lib/markdown/serializeMdxRemote.tsx
- src/pages/_app.tsx
- src/pages/docs/[...path].tsx
This PR implements ZoomableImg that is similar to Medium. User can zoom in the image as they wish! (close #389)
> feat: Implement ZoomableImg

- package.json
- pnpm-lock.yaml
- src/components/tutorial/TutorialBlock/TutorialBlock.stories.tsx
- src/components/tutorial/TutorialSearch.tsx
- src/components/tutorial/index.ts
- src/pages/tutorials/index.tsx
This commit implements fuzzy search for tutorials
> feat: Impl fuzzy search

- package.json
- pnpm-lock.yaml
- src/components/tutorial/TutorialBlock/TutorialBlock.tsx
- src/components/tutorial/TutorialFilters/TutorialFilters.tsx
- src/components/tutorial/TutorialPipeline.tsx
- src/components/tutorial/TutorialTableOfContent.tsx
- src/components/tutorial/TutorialThemeImage.tsx
- src/components/tutorial/index.ts
- src/lib/instill/getCvTaskIconAndLabel.tsx
- src/pages/tutorials/[...path].tsx
This PR refactors the style of the header at TutorialDetails page
> refactor: Refactor tutorial detail header

- src/components/tutorial/TutorialBlock/TutorialBlock.stories.tsx
- src/components/tutorial/TutorialBlock/TutorialBlock.tsx
- src/components/tutorial/TutorialImagePlaceholder.tsx
- src/components/tutorial/TutorialThemeImage.tsx
- src/components/tutorial/index.ts
- src/lib/instill/index.ts
- src/lib/instill/validateTutorialMeta.ts
- src/pages/tutorials/[...path].tsx
- src/pages/tutorials/index.tsx
- src/types/instill.ts
- tailwind.config.js
- tutorials/build-a-sync-cls-pipeline.mdx
- tutorials/build-an-async-det-pipeline.mdx
- tutorials/build-test-pipeline.mdx
This PR force maintainer to explicit specific the image place holder color of Tutorial
> feat: explicit specific image place holder color of Tutorial

- README.md
- src/components/landing/CaseStudy/ControlPanel/ControlPanel.tsx
- src/components/tutorial/TutorialBlock/TutorialBlock.stories.tsx
- src/components/tutorial/TutorialFilters/TutorialFilters.tsx
- src/components/tutorial/TutorialList.tsx
- src/components/tutorial/TutorialSimilarUseCases.tsx
- src/components/tutorial/index.ts
- src/components/ui/Nav/Nav.tsx
- src/components/ui/Nav/TutorialPageLink.tsx
- src/components/ui/PageHead.tsx
- src/lib/github/index.ts
- src/lib/instill/prepareTutorial.ts
- src/lib/instill/validateTutorialMeta.ts
- src/pages/index.tsx
- src/pages/tutorials/[...path].tsx
- src/pages/tutorials/index.tsx
- src/types/instill.ts
- tutorials/build-a-sync-cls-pipeline.mdx
- tutorials/build-an-async-det-pipeline.mdx
- tutorials/build-test-pipeline-2.mdx
- tutorials/build-test-pipeline.mdx
This PR implements similar use case section at TutorialDetails page.
> feat: implement similar use case section at TutorialDetails page

- src/components/tutorial/TutorialBlock/TutorialBlock.tsx
- src/components/ui/HorizontalLine.tsx
- src/components/ui/LastEditedInfo.tsx
- src/components/ui/index.ts
- src/lib/github/index.ts
- src/lib/github/type.ts
- src/pages/docs/[...path].tsx
- src/pages/tutorials/[...path].tsx
This commit implement details of commit author included author name, author link and author avatar
> feat: Implement commit details

- src/lib/markdown/remark-twitter.mjs
- src/lib/markdown/serializeMdxRemote.tsx
This PR adds remark-twitter plugin to make us embed twitter card in markdown file.
> feat: add remark-twitter plugin

- src/components/tutorial/TutorialPublishInfo.tsx
- src/components/tutorial/TutorialTableOfContent.tsx
- src/components/tutorial/index.ts
- src/pages/docs/[...path].tsx
- src/pages/tutorials/[...path].tsx
- src/styles/docs.css
- tailwind.config.js
This PR refactor the style of tutorial page, it also alter the font-size of tailwind-typography. enlarges the font-size of each header.
> refactor: refactor tutorial style

- src/pages/tutorials/[...path].tsx
This PR fixes tutorial page's title meta
> fix: fix meta title

- src/components/tutorial/TutorialThemeImage.tsx
- src/components/ui/BackToPreviousPageLink.tsx
- src/components/ui/PageHero.tsx
- src/pages/tutorials/[...path].tsx
This PR updates the PageHero style.
> feat: update the hero style

- .github/workflows/deploy-prod.yml
This PR removes unnecessary steps in deploy-prod action to avoid unexpected failure
> chore: remove unnecessary steps in deploy-prod action

- package.json
- pnpm-lock.yaml
- src/components/landing/Hero/GitHubCtaButton.tsx
- src/components/tutorial/TutorialBlock/TutorialBlock.tsx
- src/components/tutorial/TutorialPublishInfo.tsx
- src/components/tutorial/TutorialThemeImage.tsx
- src/components/ui/ImageGallery/ImageGallery.tsx
- src/components/ui/ImageGallery/Thumb.tsx
- src/components/ui/ImageGallery/ZoomedImageGallery.tsx
- src/components/ui/MdxZoomableImg.tsx
- src/components/ui/ModalBase.tsx
- src/components/ui/ZoomableImg.tsx
- tailwind.config.js
This PR implement advanced ImageGallery, it also
- Enlarge the tailwind-typography p tag's margin (close #411)
- Update landing hero CTA link (close #396)
- fix ImageGallery bug (close #410)
> feat: Implement advanced ImageGallery

- .github/workflows/check-main-lighthouse-score.yml
- .github/workflows/cron-remove-old-artifacts.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/test-and-deploy-staging.yml
- .github/workflows/unit-test.yml
- .github/workflows/webpack-diff.yml
Because
- Make the naming of the github workflow consistent
This commit
- Rename the workflow name of this repo
> refactor: rename workflow name

- docs/core-concepts/pipeline.mdx
- src/components/ui/ImageGallery/ImageGallery.tsx
- src/components/ui/ImageGallery/ZoomedImageGallery.tsx
- src/components/ui/MdxImageGallery.tsx
- src/components/ui/ZoomableImg.tsx
- src/pages/_app.tsx
- tailwind.config.js
- tutorials/vdp-cow-counter.mdx
- tutorials/vdp-streamlit-yolov7.mdx
Because
- The typography need to be adjusted
- Image's caption in content page doesn't show correctly
This commit
- Refactor typography
- Fix image caption
> feat: update typography style and fix image caption issue for content page

- blog/why-instill-ai-exists.mdx
- docs/start-here/roadmap.mdx
Because
- we want to keep the blog articles up to date
This commit
- refactor blog article
- update roadmap
> docs(blog,start-here): refactor blog article

- src/components/ui/MdxQuoteBlock.tsx
- src/components/ui/index.ts
- src/pages/_app.tsx
Because
- Specific small component(props: content, source) to add on documentation.
This commit
- Add this component with props(content, source) on docs files(mdx).
> add: quote block

- docs/start-here/roadmap.mdx
Because
- ✅ is straightforward, no need to add description
This commit
- remove info block
> docs(start-here): remove info block

- CONTRIBUTING.md
Because
- We need better guideline for contributor
This commit
- update guideline for better contribution experience
> feat: update CONTRIBUTING guideline

- src/components/tutorial/TutorialBlock/TutorialBlock.tsx
- src/components/tutorial/TutorialFilters/TutorialFilters.tsx
- src/components/tutorial/TutorialPipelineLabel.tsx
- src/lib/instill/getAiTaskIconAndLabel.tsx
- src/lib/instill/validateTutorialMeta.ts
- src/pages/tutorials/[...path].tsx
- src/pages/tutorials/index.tsx
- src/types/instill.ts
Because
- #455 
This commit
- support Null connectors and aiTask
> feat: support Null connectors and aiTask

- src/components/ui/ArticleSimilarPosts.tsx
- src/pages/tutorials/[...path].tsx
Because
- #452 
This commit
- fix similar use case index issue
- close #452
> fix: fix similar use case index issue

- src/pages/blog/[...path].tsx
- src/pages/tutorials/[...path].tsx
Because
- #461 
This commit
- update similar use cases section label at docs and tutorials page
> chore: update similar use cases section label at docs and tutorials page

- .github/workflows/pr-semantic.yml
Because
- #443
This commit
- add PR semantic check workflow
- close #443
> feat: add PR semantic check workflow

- CONTRIBUTING.md
Because
- We need to explain the purpose of each frontmatter field
This commit
- update contributing guide
> feat: update contributing guide

- src/components/ui/Footer/AnimateSlogan.css
- src/components/ui/Footer/AnimateSlogan.tsx
Because
- we want to update the footer to be consistent with the one-liner
This commit
- update footer to `UNSTRUCTURED DATA INFRASTRUCTURE MADE FOR ALL`
- update footer animation and put `MADE FOR ALL` in a new line
> chore: update footer

- src/components/ui/Nav/Nav.tsx
Because
- Announcement bar in mobile view didn't display correctly
This commit
- fix announcement bar at mobile view
> fix: fix announcement bar at mobile view

- src/components/ui/Nav/Nav.tsx
Because
- we want to refactor the banner text
This commit
- update the banner text
> chore: update banner text

- src/components/career/PositionList/CareerPositionListItem.tsx
- src/components/career/PositionList/PositionList.tsx
Because
- #484 
This commit
- remove post date in career list page
- close #484
> feat: remove post date in career list page

- docs/core-concepts/ai-task.mdx
Because
- we want to keep the documentation up to date
This commit
- update the model version
> docs(core-concept): fix ai task model

- src/components/docs/Nav/Item.tsx
- tailwind.config.js
Because
- Tailwind didn't recognize content.config.ts
This commit
- fix tailwind didn't recognize content.config.ts issue
> fix: fix tailwind didn't recognize content.config.ts issue

- src/components/ui/PageHead.tsx
Because
- favicon on blog and tutorial page is wrong
This commit
- The PR fixed above issue
> fix: fix favicon on blog and tutorial

- CONTRIBUTING.md
- package.json
- pnpm-lock.yaml
- src/components/tutorial/TutorialFilters/TutorialFilters.tsx
- src/lib/instill/getAiTaskIconAndLabel.tsx
- src/lib/instill/validateTutorialMeta.ts
- src/types/instill.ts
Because
- we want to include new AI tasks as tutorial labels
This commit
- bump up the design system package version
- support more AI tasks as tutorial labels
> chore: update design system to include new ai tasks

- docs/start-here/faq.mdx
- src/components/ui/MdxToggleBlock.tsx
- src/pages/_app.tsx
- src/styles/docs.css
will close this issue: https://github.com/instill-ai/instill.tech/issues/531
Because
- Right now we are using the regular markdown toggle syntax and then cover custom style on it to implement toggle block. Here is the implementation
```
<details>
<summary></summary>
</details>
```
This commit
- dedicated toggle block (with component name ToggleBlock) with MDX and refactor all the toggle block in docs to adapt this new MDX component.
> feat: dedicated toggle block component (#531)

- src/components/ui/PricingPlanLayout.tsx
- src/components/ui/index.ts
- src/pages/pricing.tsx
Because
- Before the release of console, we need to add pricing page on instill.tech
This commit
- add pricing page
> feat: [INS-327] add pricing page

- src/components/landing/Hero/ConsoleCtaButton.tsx
- src/components/landing/Hero/Hero.tsx
- src/components/ui/CommonCtaButton.tsx
- src/components/ui/Nav/Nav.tsx
- src/components/ui/SecureYourSpot.tsx
Because
- Preparing the upcoming console cloud release
This commit
- update cta to point to console.instill.tech
> feat: [INS-598] update cta to point to console.instill.tech

- src/components/ui/PricingPlanLayout.tsx
- src/pages/pricing.tsx
Because
- add small qol on pricing page
This commit
- update pricing cta link
> feat: [INS-599] update pricing cta link

- src/components/ui/Nav/Nav.tsx
- src/components/ui/Nav/PricingPageLink.tsx
Because
- Pricing link is missing on Nav
This commit
- add pricing link on Nav
> feat: [INS-619] add pricing link on Nav

- src/pages/pricing.tsx
Because
- we want to update the monthly fee for the Starter plan
This commit
- update pricing page
> chore(pricing): update starter plan

- docs/vdp/roadmap.mdx
Because
- the roadmap is out of date
This commit
- update roadmap
> docs(documentation): update roadmap

- blog/why-instill-ai-exists.mdx
- src/components/early-access/EarlyAccessHero.tsx
- src/components/ui/Nav/Nav.tsx
- src/components/ui/SecureYourSpot.tsx
Because
- announcement bar is out of date
This commit
- update announcement bar
> feat: update announcement bar

- src/components/ui/PricingPlanLayout.tsx
- src/pages/pricing.tsx
Because
- The style is not correct 
This commit
- fix pricing page style
> fix: fix pricing page style

- src/components/landing/Vdp/VdpFlow/VdpFlow.tsx
- src/components/ui/Footer/Footer.tsx
- src/components/ui/Footer/Tab.tsx
Because
- We have new footer structure and naming
This commit
- add support section into footer
> feat: [INS-774] add support section into footer

- tutorials/vdp-101-7-create-trigger-parse-an-async-pipeline.mdx
- tutorials/vdp-cow-counter.mdx
Because
- table border is not aligned 
This commit
- fix the border of the tutorial table
- add the ASYNC pipeline output sample for Airbyte destination PostgreSQL
> docs(tutorial): fix table border and add table in 101 tutorial

- src/components/docs/DocsLayout.tsx
- src/components/docs/Nav/Nav.tsx
- src/components/docs/Nav/SubNav.tsx
- src/components/docs/ThemeToggle/ThemeToggle.tsx
- src/pages/docs/[...path].tsx
Because
- The gradient is not consistent between the light mode and the dark mode. 
This commit
- make it consistent
> refactor: gradient update for dark mode INS-651

- content.config.tsx
Because
- update model and vdp logo
This commit
- update model and vdp logo
> chore: update model and vdp logo

- src/components/docs/ArticleNavigationButton.tsx
- src/components/docs/Nav/Nav.tsx
- src/components/docs/Nav/SubNav.tsx
- src/pages/docs/[...path].tsx
- tailwind.config.js
Because
- we want to have the blur opacity effect on the navbar
- Shrink the size of the font 
This commit
- update styles
> feat: update the nav and font style

- content.config.tsx
- docs/vdp/data-connectors/overview.mdx
- docs/vdp/data-connectors/pinecone.mdx
Because
- we need docs for Pinecone data connector
This commit
- adds docs for Pinecone data connector
> chore: added docs for pinecone

- src/components/ui/PricingPlanLayout.tsx
- src/pages/pricing.tsx
Because
- update pricing page
This commit
- update pricing page
> chore: update pricing page

- next.config.mjs
- src/components/docs/LocaleSwitcher.tsx
- src/components/ui/Nav/DocsPageLink.tsx
Because
- We changed docs entry point
This commit
- update links of docs entry point
> feat: update links of docs entry point

- src/components/docs/LocaleSwitcher.tsx
- src/pages/docs/[...path].tsx
- src/pages/docs/index.tsx
Because
- gitHub edit, prev and next page, lang switch dropdown
This commit
- gitHub edit, prev and next page, lang switch dropdown
> fix: gitHub edit path, prev and next page, lang switch dropdown, docs default redirect

- next.config.mjs
- src/pages/docs/index.tsx
Because
- we need redirection url for docs content
This commit
- redirection url for docs content
> feat: redirection url for docs content

- .env.test
- .github/CONTRIBUTING.md
- .github/DOCS-CONTRIBUTING.md
- .npmrc
- README.md
Because
- We want to help our contributor better understand our workflow
This commit
- update contribution docs
> feat(docs): update contribution docs

- blog/celebrate-Hacktoberfest-2023.mdx
Because
- we want to keep the content up-to-date
This commit
- change the headers
- update the issue labels
- correct typos
> docs(blog): update Hacktoberfest blog content

- .github/workflows/deploy-prod.yml
- .github/workflows/test-and-deploy-staging.yml
Because
- Deployment workflow is lacking the scope
This commit
- fix deployment workflow issue
> fix(cicd): fix deployment workflow issue

- blog/celebrate-Hacktoberfest-2023.mdx
Because
- orientation video has been made
This commit
- update the link of the video
> docs(blog): include orientation video and refactor content of blog article

- docs/vdp/core-concepts/pipeline.en.mdx
- docs/vdp/core-concepts/pipeline.zh_CN.mdx
- docs/vdp/operators/overview.en.mdx
Because
- the VDP documentation is not completed
This commit
- update VDP documentation
> docs(vdp): update pipeline doc

- src/components/hacktoberfest/Hero/Headline.tsx
- src/components/hacktoberfest/Hero/Hero.tsx
- src/components/hacktoberfest/Nav/Nav.tsx
- src/pages/index.tsx
Because
- mobile version
This commit
- mobile version
> chore: mobile version

- src/components/ui/Footer/Footer.tsx
- src/pages/index.tsx
Because
- update landing page content
This commit
- update landing page content
> chore: update landing page content

- src/lib/mailchimp/mailchimp.ts
- src/styles/global.css
Because
- support update for new Builder in mailchip
This commit
- support update for new Builder in mailchip
> chore: newsletter support update for new Builder in mailchip

- docs/v0.4.1-alpha/quickstart.en.mdx
- docs/v0.4.1-alpha/quickstart.zh_CN.mdx
- docs/v0.4.1-alpha/vdp/connectors/instill-model.en.mdx
- docs/v0.4.1-alpha/vdp/connectors/instill-model.zh_CN.mdx
- tutorials/model-oss-llm.mdx
Because
- wording improvement is still applicable for the content
This commit
- polish the article
- fix typos in many places
> docs(tutorial): polish model open-source LLMs

- src/pages/index.tsx
- src/styles/global.css
Because
- update newsletter css
This commit
- update newsletter css
> chore: update newsletter css

- .github/DOCS-CONTRIBUTING.md
- CONTRIBUTING.md
Because
- update versioning docs
This commit
- update versioning docs
> chore: update versioning docs

- docs/v0.4.1-alpha/core/concepts/pipeline.en.mdx
- docs/v0.4.1-alpha/core/concepts/pipeline.zh_CN.mdx
- docs/v0.4.1-alpha/model/use.en.mdx
- docs/v0.4.1-alpha/model/use.zh_CN.mdx
- docs/v0.4.1-alpha/quickstart.en.mdx
- docs/v0.4.1-alpha/quickstart.zh_CN.mdx
- docs/v0.4.1-alpha/vdp/app-connectors/numbers-protocol.en.mdx
- docs/v0.4.1-alpha/vdp/app-connectors/numbers-protocol.zh_CN.mdx
- docs/v0.4.1-alpha/vdp/data-connectors/airbyte.en.mdx
- docs/v0.4.1-alpha/vdp/data-connectors/airbyte.zh_CN.mdx
- docs/v0.4.1-alpha/vdp/operators/base64.en.mdx
- docs/v0.4.1-alpha/vdp/operators/base64.zh_CN.mdx
- docs/v0.4.1-alpha/vdp/operators/end.en.mdx
- docs/v0.4.1-alpha/vdp/operators/end.zh_CN.mdx
- docs/v0.4.1-alpha/vdp/operators/json.en.mdx
- docs/v0.4.1-alpha/vdp/operators/json.zh_CN.mdx
- docs/v0.4.1-alpha/vdp/operators/rest.en.mdx
- docs/v0.4.1-alpha/vdp/operators/rest.zh_CN.mdx
- docs/v0.4.1-alpha/vdp/operators/start.en.mdx
- docs/v0.4.1-alpha/vdp/operators/start.zh_CN.mdx
- docs/v0.4.1-alpha/vdp/operators/textextraction.en.mdx
- docs/v0.4.1-alpha/vdp/operators/textextraction.zh_CN.mdx
- draft/vdp-101-3-create-your-first-pipeline.mdx
- draft/vdp-101-6-pipeline-modes.mdx
- next.config.mjs
- src/components/landing/CodeShowcase/CodeShowcase.tsx
- src/components/landing/HowItWorks/HowItWorks.tsx
- tutorials/model-oss-llm.mdx
- tutorials/vdp-streamlit-yolov7.mdx
Because
- fix broken links on .mdx files
This commit
- fix broken links on .mdx files
> chore: fix broken links on .mdx files

- src/components/docs/LeftSidebar/LeftSidebar.tsx
Because
- update left sidebar margin scrollbar
This commit
- update left sidebar margin scrollbar
> chore: update left sidebar margin scrollbar

- docs/v0.4.1-alpha/vdp/ai-connectors/instill-model.en.mdx
- docs/v0.4.1-alpha/vdp/ai-connectors/instill-model.zh_CN.mdx
Because
- update the docs numbering https://github.com/instill-ai/community/issues/481
This commit
- update the docs numbering https://github.com/instill-ai/community/issues/481
> chore: update the docs numbering

- docs/v0.4.1-alpha/quickstart.en.mdx
- docs/v0.4.1-alpha/quickstart.zh_CN.mdx
- docs/v0.4.1-alpha/sdk/typescript.en.mdx
- docs/v0.4.1-alpha/sdk/typescript.zh_CN.mdx
- docs/v0.5.0-alpha/quickstart.en.mdx
- docs/v0.5.0-alpha/quickstart.zh_CN.mdx
- docs/v0.6.0-alpha/quickstart.en.mdx
- docs/v0.6.0-alpha/quickstart.zh_CN.mdx
- tutorials/model-oss-llm.mdx
Because
- we want to show how to use the pipeline in the user's code base
This commit
- add low-code triggering pipeline section in the tutorial
> docs(docs,tutorial): add low-code section tutorials/model-oss-llm.mdx

- blog/hacktoberfest-2023-closing.mdx
Because
- update twitter status link
This commit
- update twitter status link
> chore: update twitter status link

- src/components/landing/jumbotron/Jumbotron.tsx
- src/lib/jumbotron/llava7b.ts
- src/lib/jumbotron/seoArticle.ts
- src/lib/jumbotron/stabilityAIOpenAISticker.ts
- src/lib/jumbotron/yolov7.ts
- src/styles/global.css
Because
- fix card swiping animation
This commit
- fix card swiping animation
> chore: Namananand/ins 3107 fix card swiping animation

- src/components/ui/PricingInfoCard.tsx
- src/components/ui/index.ts
- src/pages/pricing.tsx
Because
- need pricing on website
This commit
- need pricing on website
> chore: Namananand/ins 3030 need pricing on website

- src/pages/api/instill-api-proxy.ts
Because
- Add cf header to bypass cloudflare
This commit
- Add cf header to bypass cloudflare
> feat: Add cf header to bypass cloudflare

- src/components/about/Company.tsx
- src/components/about/Mission.tsx
- src/components/about/OurPartner.tsx
- src/components/about/Teams.tsx
- src/components/ui/Nav/ChangelogLink.tsx
- src/components/ui/Nav/Nav.tsx
- src/middleware.ts
- src/pages/pricing.tsx
Because
- add changelog link
This commit
- add changelog link
> chore: add changelog link

- src/components/landing/jumbotron/AskOnPage.tsx
- src/components/landing/jumbotron/Llama2Chat.tsx
- src/components/landing/jumbotron/ResponderWithSpeech.tsx
- src/components/landing/jumbotron/SEOArticleWriter.tsx
- src/components/landing/jumbotron/StabilityAIOpenAISticker.tsx
- src/components/landing/jumbotron/WebpageSummarization.tsx
- src/components/landing/jumbotron/YOLOv7.tsx
- src/styles/global.css
Because
- object detection card allows image uploading
This commit
- object detection card allows image uploading
> chore: namananand/ins 3353 object detection card allows image uploading

- src/components/landing/jumbotron/ResponderWithSpeech.tsx
- src/styles/global.css
Because
- llama chatbox
This commit
- llama chatbox
> fix: llama chatbox

- content.config.tsx
- src/components/landing/jumbotron/AskOnPage.tsx
- src/components/landing/jumbotron/Llama2Chat.tsx
- src/components/landing/jumbotron/ResponderWithSpeech.tsx
- src/components/landing/jumbotron/SEOArticleWriter.tsx
- src/components/landing/jumbotron/StabilityAIOpenAISticker.tsx
- src/components/landing/jumbotron/WebpageSummarization.tsx
- src/components/ui/Nav/Nav.tsx
Because
- update jumbotron text and add API reference
This commit
- update jumbotron text and add API reference
> chore: update jumbotron text and add API reference

- CONTRIBUTING.md
- src/components/landing/Hero/Hero.tsx
Because
- add producthunt link
This commit
- add producthunt link
> chore: add producthunt link

- src/pages/pricing.tsx
Because
- fix team pricing
This commit
- fix team pricing
> fix: fix team pricing

- src/components/ui/Nav/Nav.tsx
Because
- console url
This commit
- console url
> fix: console url

- src/pages/pricing.tsx
Because
- update book meeting link
This commit
- update book meeting link
> fix: update book meeting link

- src/components/ui/Footer/Footer.tsx
Because
- add changelog link into footer
This commit
- add changelog link into footer
> chore: add changelog link into footer

- docs/v0.10.0-beta/sdk/typescript.en.mdx
- docs/v0.10.0-beta/sdk/typescript.zh_CN.mdx
- docs/v0.4.1-alpha/sdk/typescript.en.mdx
- docs/v0.4.1-alpha/sdk/typescript.zh_CN.mdx
- docs/v0.5.0-alpha/sdk/typescript.en.mdx
- docs/v0.5.0-alpha/sdk/typescript.zh_CN.mdx
- docs/v0.6.0-alpha/sdk/typescript.en.mdx
- docs/v0.6.0-alpha/sdk/typescript.zh_CN.mdx
- docs/v0.8.0-beta/sdk/typescript.en.mdx
- docs/v0.8.0-beta/sdk/typescript.zh_CN.mdx
- docs/v0.9.0-beta/sdk/typescript.en.mdx
- docs/v0.9.0-beta/sdk/typescript.zh_CN.mdx
Because
- update `@instill-ai/typescript-sdk` to `instill-sdk`
This commit
- update `@instill-ai/typescript-sdk` to `instill-sdk`
> docs: update @instill-ai/typescript-sdk to instill-sdk

- src/components/ui/Footer/Footer.tsx
- src/components/ui/Nav/Nav.tsx
Because
- add glass effect to navbar and api reference link
This commit
- add glass effect to navbar and api reference link
> chore: Namananand/ins 3585 add glass effect to navbar and api reference link

- src/components/ui/Nav/LoginPageLink.tsx
- src/components/ui/Nav/Nav.tsx
Because
- add login and signup link navbar
This commit
- add login and signup link navbar
> chore: add login and signup link navbar

- public/images/social/wistron.svg
- src/components/landing/Social.tsx
Because
- add `https://www.wistron.com/` to customer list on landing page
This commit
- add `https://www.wistron.com/` to customer list on landing page
> chore: add https://www.wistron.com/ to customer list on landing page

- src/components/about/Teams.tsx
Because
- we want to keep the member list up-to-date
This commit
- update member list
- switch the colours of the engineer and back office departments
> chore(about): update member list

- .github/DOCS-CONTRIBUTING.md
- CONTRIBUTING.md
- draft/vdp-101-1-introduction.mdx
- draft/vdp-101-2-quickstart.mdx
- draft/vdp-101-3-create-your-first-pipeline.mdx
- draft/vdp-101-4-how-to-trigger-a-sync-pipeline.mdx
- draft/vdp-101-5-how-to-parse-vdp-responses.mdx
- draft/vdp-101-6-pipeline-modes.mdx
- draft/vdp-101-7-create-trigger-parse-an-async-pipeline.mdx
- draft/vdp-cow-counter.mdx
- draft/vdp-discord-text-generation.mdx
- draft/vdp-streamlit-yolov7.mdx
- src/types/instill.ts
- tutorials/model-oss-llm.mdx
- tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx
Because
- unify the metadata with updated one
This commit
- unify the metadata with updated one
> chore: unify the metadata with updated one

- src/components/landing/jumbotron/AskOnPage.tsx
- src/components/landing/jumbotron/Llama2Chat.tsx
- src/components/landing/jumbotron/ResponderWithSpeech.tsx
- src/components/landing/jumbotron/SEOArticleWriter.tsx
- src/components/landing/jumbotron/StabilityAIOpenAISticker.tsx
- src/components/landing/jumbotron/WebpageSummarization.tsx
- src/components/landing/jumbotron/YOLOv7.tsx
Because
- swiper autoplay stop if when under jumbotron
This commit
- swiper autoplay stop if when under jumbotron
> fix: swiper autoplay stop if when under jumbotron

- src/components/tutorial/TutorialFilters/TutorialFilters.tsx
- src/lib/instill/getAiTaskIconAndLabel.tsx
- src/lib/instill/validateTutorialMeta.ts
- src/types/instill.ts
- tutorials/llava-v1-6-7b.mdx
Because
- add new aiType VisualQuestionAnswering
This commit
- add new aiType VisualQuestionAnswering
> feat: add new aiType VisualQuestionAnswering

- src/lib/jumbotron-sdk/llava7b.ts
Because
- update API link
This commit
- update API link
> chore: update API link

- .github/DOCS-CONTRIBUTING.md
- CONTRIBUTING.md
- src/components/landing/jumbotron/Llama27bVsLlama27bChat.tsx
- src/components/landing/jumbotron/index.ts
- src/components/ui/MdxLlama27bVsLlama27bChat.tsx
- src/components/ui/index.ts
- src/lib/jumbotron-sdk/index.ts
- src/lib/jumbotron-sdk/llama27bVsllama27bChat.ts
- src/pages/_app.tsx
Because
- add Llama27bVsLlama27bChat
This commit
- add Llama27bVsLlama27bChat
> feat: add Llama27bVsLlama27bChat

- src/components/landing/Model/ModelComponent.tsx
Because
- task name toLowerCase
This commit
- task name toLowerCase
> chore: task name toLowerCase

- src/components/landing/Hero/Headline.tsx
- src/components/landing/Hero/Hero.tsx
- src/components/landing/HowItWorks/HowItWorks.tsx
- src/components/landing/Model/ModelComponent.tsx
This commit
- fix the jumbotron grammar mistake
- remove the product hunk badge
- make the task name more user-friendly
> chore(website): fix jumbotron grammar mistake and remove product hunt badge

- src/components/landing/Community/Community.tsx
- src/components/landing/Community/StayInTheLoop.tsx
- src/components/landing/InstillCloud.tsx
- src/components/ui/Nav/Nav.tsx
- src/components/ui/StayInTheLoop.tsx
- src/components/ui/SubscribeNewsletterForm.tsx
- src/pages/career/index.tsx
Because
- fix newsletter style inconsistency
This commit
- fix newsletter style inconsistency and dark and light mode
> feat :Namananand/ins 3976 fix newsletter style inconsistency

- public/assets/pinecone.svg
- src/components/landing/Connector/ConnectorComponent.tsx
- src/components/landing/Operator/OperatorComponent.tsx
- src/middleware.ts
Because
- middleware redirection
This commit
- middleware redirection
> fix: middleware redirection

- src/components/ui/PageHead.tsx
- src/pages/blog/[...path].tsx
Because
-  json-ld parsing
This commit
- json-ld parsing
> fix: json-ld parsing

- .github/workflows/test-and-deploy-staging.yml
Because
- remove storybook release pipeline
This commit
- remove storybook release pipeline
> refactor: remove storybook release pipeline

- docs/sdk/typescript.en.mdx
Because
- update typescript docs
This commit
- update typescript docs
> chore: update typescript docs

- src/components/ui/Footer/Footer.tsx
Because
- instill Cloud footer link fix
This commit
- instill Cloud footer link fix
> fix: instill Cloud footer link fix

- src/components/landing/Connector/ConnectorComponent.tsx
- src/components/landing/Operator/OperatorComponent.tsx
- src/pages/component.tsx
Because
- fix version to release_stage 
This commit
- fix version to release_stage
> fix: fix version to release_stage 

- src/pages/cookie.mdx
- src/pages/newsletter.tsx
- src/styles/global.css
Because
- type and bg fix
This commit
- type and bg fix
> fix: type and bg fix

- docs/core/deployment/docker-compose.en.mdx
- docs/core/deployment/docker-compose.zh_CN.mdx
- tutorials/llava-v1-6-13b.mdx
- version.mjs
Because
- Doc version is outdated.
This commit
- Update doc version to v0.29.0-beta.
> chore: update doc version

- src/components/about/Teams.tsx
Because
- team member details
This commit
- team member details
> fix: team member details

- public/images/about/bg-2.svg
- public/images/about/bg-pipeline.svg
- src/components/about/AboutHero.tsx
- src/components/about/Company.tsx
- src/components/about/Mission.tsx
- src/components/about/OurCoreValues.tsx
- src/components/about/OurPartner.tsx
- src/components/about/Teams.tsx
- src/pages/about.tsx
- src/styles/global.css
Because
- about us page
This commit
- about us page
> feat: about us page

- src/lib/jumbotron-sdk/webpageSummarization.ts
Because
- update webpage summary link
This commit
- update webpage summary link
> chore: update webpage summary link

- src/pages/404.tsx
- src/pages/docs/[...path].tsx
Because
- 404 page error on docs page
This commit
- 404 page error on docs page
> fix: 404 page error on docs page

- src/components/ui/Nav/Nav.tsx
Because
- navbar updates
This commit
- navbar updates
> feat: Namananand/ins 4197 navbar updates

- src/components/ui/Nav/Nav.tsx
- src/components/ui/SubscribeNewsletterForm.tsx
- src/pages/_app.tsx
- src/pages/newsletter.tsx
- src/styles/global.css
Because
- newsletter page
This commit
- newsletter page
> feat: Namananand/ins 4376 newsletter page

- content.config.tsx
- src/components/docs/ArticleNavigationButton.tsx
- src/components/docs/LeftSidebar/Section.tsx
- src/components/docs/LocaleSwitcher.tsx
- src/components/docs/Nav/Item.tsx
- src/components/docs/Nav/Nav.tsx
- src/components/landing/HowItWorks/HowItWorksRow/HowItWorksRow.stories.tsx
- src/components/landing/HowItWorks/IconsCube/IconsCube.stories.tsx
- src/components/ui/ContributeLinks.tsx
- src/components/ui/LastEditedInfo.tsx
- src/components/ui/MdxCtaButton.tsx
- src/components/ui/TableOfContent.tsx
- src/styles/docs.css
Because
- docs page update
This commit
- docs page update
> feat: Namananand/ins 4383 docs page update

- src/components/article/ArticleHero.tsx
- src/components/article/ArticleList.tsx
- src/components/article/ArticleSearch.tsx
- src/components/article/ArticleType.tsx
- src/components/tutorial/StartBuildingBlock.tsx
- src/components/ui/PageHero.tsx
- src/pages/articles/index.tsx
- src/pages/blog/[...path].tsx
- src/pages/tutorials/[...path].tsx
Because
- mobile version blog and tutorial
This commit
- mobile version blog and tutorial
> feat: mobile version blog and tutorial

- src/components/career/CareerHero.tsx
- src/pages/career/[slug].tsx
- src/pages/career/index.tsx
Because
- career mobile view update
This commit
- career mobile view update
> feat: Namananand/ins 4282 career mobile view update

- src/components/landing/Connector/ConnectorComponent.tsx
- src/components/landing/Operator/OperatorComponent.tsx
- src/pages/component.tsx
Because
- component mobile view update
This commit
- component mobile view update
> feat: Namananand/ins 4286 component mobile view update

- src/components/article/StartBuildingBlock.tsx
- src/components/pricing/PriceTable.tsx
- src/pages/pricing.tsx
Because
- pricing mobile view update
This commit
- pricing mobile view update
> feat: Namananand/ins 4279 pricing mobile view update

- src/components/policy/PolicyPageLayout.tsx
Because
- privacy policy and cookies
This commit
- privacy policy and cookies
> feat: privacy policy and cookies

- src/components/landing/Hero/Hero.tsx
- src/components/ui/Nav/Nav.tsx
Because
- navbar mobile version fix
This commit
- navbar mobile version fix
> fix: navbar mobile version fix

- blog/hackathon-2024-may.mdx
Because
- hackathon
This commit
- hackathon
> chore(blog): hackathon

- blog/hackathon-2024-may.mdx
Because
- Instill Credits need adjustment
This commit
- Update the number for Instill Credits and delete how much it worths.
> docs(blog): update hackathon blog

- .eslintrc.json
- src/components/about/Teams.tsx
- src/components/docs/Nav/Nav.tsx
- src/components/hacktoberfest/Nav/DocsPageLink.tsx
- src/components/hacktoberfest/SubscribeNewsletterForm.tsx
- src/components/landing/Hero/Hero.tsx
- src/components/landing/HowItWorks/HowItWorksRow/HowItWorksRow.tsx
- src/components/landing/InstillHero.tsx
- src/components/landing/NoCodeInterface.tsx
- src/components/landing/Operator/OperatorComponent.tsx
- src/components/landing/Slide.tsx
- src/components/landing/Social.tsx
- src/components/landing/Vdp/Vdp.tsx
- src/components/landing/Vdp/VdpArrowBlock/VdpArrowBlock.tsx
- src/components/landing/jumbotron/AskOnPage.tsx
- src/components/landing/jumbotron/Llama2Chat.tsx
- src/components/landing/jumbotron/SEOArticleWriter.tsx
- src/components/landing/jumbotron/StabilityAIOpenAISticker.tsx
- src/components/landing/jumbotron/YOLOv7.tsx
- src/pages/blog/[...path].tsx
- src/pages/tutorials/[...path].tsx
Because
- lint warning
This commit
- lint warning
> fix: lint warning

- content.config.tsx
- docs/vdp/app-connectors/slack.en.mdx
- docs/vdp/app-connectors/slack.zh_CN.mdx
- public/locales/en/common.json
- public/locales/zh_CN/common.json
- update_connector_operator.sh
Because
- We want the users to integrate Slack into pipeline.
This commit
- Add doc for Slack component
> docs(vdp): Add slack component

- content.config.tsx
- docs/component/generics/iterator.en.mdx
- docs/component/generics/iterator.zh_CN.mdx
- public/locales/en/common.json
- public/locales/zh_CN/common.json
Because
- We lack documentation for the iterator component.
This commit
- Adds documentation for the iterator component.
> docs(vdp): add iterator component

- package.json
- pnpm-lock.yaml
- src/components/ui/Nav/Nav.tsx
Because
- add navbar mobile
This commit
- add navbar mobile
> feat: add navbar mobile

- docs/component/app/slack.en.mdx
- docs/component/app/slack.zh-CN.mdx
Because
- we update slack component
This commit
- update the document for slack component
> chore(vdp): modify slack component

- src/lib/instill-sdk/component.ts
- src/lib/instill-sdk/model.ts
Because
- update the api route prefix
This commit
- update the api route prefix
> fix: update the api route prefix

- src/components/landing/Component/ComponentCard.tsx
- src/components/landing/HowItWorks/HowItWorks.tsx
- src/pages/component.tsx
Because
- The component cards area is broken.
This commit
- Fixes component cards.
> fix(component): fix component cards

- src/components/landing/Component/ComponentCard.tsx
- src/components/landing/HowItWorks/HowItWorks.tsx
- src/lib/instill-sdk/component.ts
- src/pages/component.tsx
Because
- The component page filter is not working.
This commit
- Fixes component card page.
> fix(component): fix component card page

- .github/workflows/test-and-deploy-staging.yml
- .github/workflows/unit-test.yml
- pnpm-lock.yaml
- src/components/landing/Community/Community.tsx
Because
- (write the reason why we need to consider this PR in a list)
This commit
- (write the summary of all commits in this PR in a list)
> fix: discord typo

- docs/model/create/build.en.mdx
- docs/model/create/build.zh-CN.mdx
- docs/model/create/prepare.en.mdx
- docs/model/create/prepare.zh-CN.mdx
- docs/model/create/push.en.mdx
- docs/model/create/push.zh-CN.mdx
Because
- We have updated the model image build user flow
This commit
- update model image related docs
> chore(model): update model image related docs

- src/components/ui/Nav/HubPageLink.tsx
Because
- (write the reason why we need to consider this PR in a list)
This commit
- (write the summary of all commits in this PR in a list)
> fix: rename hub to explore

- tutorials/model-serving-on-instill-core.mdx
Because
- Model serving tutorial needs to be updated to reflect changes in Instill Model and Python SDK
This commit
- Updates tutorial according changes
> docs(tutorial): update tutorial to reflect model and sdk changes
