docs.config.tsx, src/pages/docs/core-concepts/cv-task.mdx, src/pages/docs/core-concepts/overview.mdx, src/pages/docs/development/local-development.mdx, src/pages/docs/import-models/overview.mdx, src/pages/docs/start-here/configuration.mdx, src/pages/docs/start-here/faq.mdx, src/pages/docs/start-here/getting-started.mdx
Because
- we're iterating the documentation
This commit
- add contents in `start-here/configuration`
- add `development` section
- other small documentation fixes
=> docs(start-here,core-concepts,development,import-models): add configuration and  development content

src/pages/docs/core-concepts/connector.mdx, src/pages/docs/core-concepts/pipeline.mdx, src/pages/docs/start-here/faq.mdx
Because
- we are rapidly iterating the documentation
This commit
- add release stage in `core-concepts/connector`
- reword some places
=> docs(core-concepts): add connector release stage

docs.config.tsx, src/pages/docs/destination-connectors/airbyte.mdx, src/pages/docs/destination-connectors/grpc.mdx, src/pages/docs/destination-connectors/http.mdx, src/pages/docs/destination-connectors/overview.mdx, src/pages/docs/source-connectors/grpc.mdx, src/pages/docs/source-connectors/http.mdx, src/pages/docs/source-connectors/overview.mdx
Because
- we are rapidly iterating documentation
This commit
- add connector pages
=> docs(source-connectors,destination-connectors): add connector pages

src/pages/docs/destination-connectors/airbyte.mdx, src/pages/docs/destination-connectors/grpc.mdx, src/pages/docs/destination-connectors/http.mdx, src/pages/docs/source-connectors/grpc.mdx, src/pages/docs/source-connectors/http.mdx, src/pages/docs/start-here/getting-started.mdx
Because
- we are rapidly iterating the documentation
This commit
- add connector setup guidelines
- reformat connector description
- fix typos
=> docs(source-connectors,destination-connectors): add setup guides

src/pages/docs/core-concepts/model.mdx, src/pages/docs/destination-connectors/airbyte.mdx, src/pages/docs/destination-connectors/grpc.mdx, src/pages/docs/destination-connectors/http.mdx, src/pages/docs/development/setup-local-development.mdx, src/pages/docs/import-models/artivc.mdx, src/pages/docs/import-models/github.mdx, src/pages/docs/import-models/huggingface.mdx, src/pages/docs/import-models/local.mdx, src/pages/docs/source-connectors/grpc.mdx, src/pages/docs/source-connectors/http.mdx, src/pages/docs/start-here/configuration.mdx, src/pages/docs/start-here/getting-started.mdx, src/pages/docs/tutorials/build-a-sync-cls-pipeline.mdx, src/pages/docs/tutorials/build-an-async-det-pipeline.mdx
Because
- we are rapidly iterating the documentation 
This commit
- refine wording
=> docs: refine wording

.github/workflows/cron-remove-old-artifacts.yml, .github/workflows/deploy-prod.yml
Because
- #211
This commit
- Fix URLs is not iterable issue when lighthouse action access vercel preview URL
- close #211
=> fix: fix urls is not iterable issue when lighthouse action access vercel preview url

src/pages/docs/start-here/faq.mdx
Because
- we're iterating the docs
This commit
- fix typos
=> docs: fix typo

src/pages/docs/core-concepts/cv-task.mdx, src/pages/docs/core-concepts/overview.mdx, src/pages/docs/core-concepts/pipeline.mdx, src/pages/docs/development/setup-local-development.mdx, src/pages/docs/import-models/artivc.mdx, src/pages/docs/import-models/github.mdx, src/pages/docs/prepare-models/model-card.mdx, src/pages/docs/prepare-models/overview.mdx, src/pages/docs/prepare-models/post-processing.mdx, src/pages/docs/start-here/configuration.mdx, src/pages/docs/start-here/faq.mdx, src/pages/docs/start-here/instill-cloud.mdx, src/pages/docs/tutorials/build-a-sync-cls-pipeline.mdx, src/pages/docs/tutorials/build-an-async-det-pipeline.mdx
Because
- we're iterating the docs
This commit
- use text blocks
- refactor text block style
- make block header smaller to 16px 
- change link text colour to text block colour
- reduce bottom padding
=> docs(core-concepts,development,import-models,prepare-models,start-here,tutorials): adopt text block

README.md, src/components/docs/LeftSidebar/LeftSidebar.tsx, src/components/docs/LeftSidebar/Section.tsx, src/components/docs/RightSidebar/TableOfContent.tsx, src/pages/docs/[...path].tsx, src/styles/docs.css
Because
- The selection color at code-block is too light.
- We need to indicate what section the user is currently at.
This commit
- Update selection color at code-block
- Highlight current hast at toc
=> feat: update selection color at code-block, highlight current hast at toc

README.md, docs/import-models/artivc.mdx, docs/import-models/github.mdx, docs/import-models/huggingface.mdx, docs/import-models/local.mdx, docs/start-here/getting-started.mdx, docs/tutorials/build-a-sync-cls-pipeline.mdx
Because
- we would like to have section layout unified under a topic
This commit
- make `import-models` pages have an identical `Feature` header
=> docs(import-models): unify feature section

docs/tutorials/build-an-async-det-pipeline.mdx
Because
- triggering an async pipeline should return `200 OK` with an empty body
This commit
- update the async pipeline triggering response
=> docs(tutorial): update async trigger response

docs/core-concepts/cv-task.mdx, docs/core-concepts/model.mdx, docs/start-here/faq.mdx, docs/start-here/getting-started.mdx, docs/tutorials/build-an-async-det-pipeline.mdx
Because
- referring a section title should keep its PASCAL case.
- async response empty output was reset
- cv task output was changed
This commit
- correct typos
- reset async response output
- update cv task output
=> docs(core-concepts,start-here,tutorials): refine content 

docs/import-models/github.mdx, docs/start-here/configuration.mdx
Because
- update the documentation
This commit
- add warning for importing model from GitHub using Git LFS
- update usage collection reporting frequency
=> docs: add warning for Git LFS

src/pages/_document.tsx
Because
- We want to track outbound link
This commit
-  add outbound-link tracking
=> feat: add outbound-link tracking

.github/workflows/test-and-deploy-staging.yml
Because
- rename action to better suit it behavior
This commit
-  rename deploy to staging action
=> fix: rename deploy to staging action

.github/workflows/test-and-deploy-staging.yml
Because
- Yesterday we merge an empty commit to trigger build and deploy to production's action. We need to clean it up.
This commit
- remove non necessary commit and rollback release version to 1.15.0
=> chore: remove non necessary commit and rollback release version to 1.15.0

release-please/config.json
Because
- We need to make release-bot recognize the docs prefix in the commit
This commit
-  extend release-action to include docs prefix
=> chore: extend release-action to include docs prefix

docs/tutorials/build-an-async-det-pipeline.mdx
Because
- mapping async data is now via `data_mapping_indices` field in the response payload for triggering a pipeline
This commit
- updates the documentation accordingly
=> docs(tutorials): update async pipeline outputs

README.md, docs/core-concepts/cv-task.mdx
Because
- we've refactored the [VDP Protocol](https://github.com/instill-ai/vdp/blob/main/protocol/vdp_protocol.yaml).
This commit
- add how to deploy on a different port
- refactor the CV task protocol and example codes
=> docs(core-concepts): update cv task protocol

docs.config.tsx, src/components/docs/DocsLayout.tsx, src/lib/utils/debounce.ts, src/lib/utils/handle.ts, src/lib/utils/index.ts, src/pages/docs/[...path].tsx
This commit clean up all the default export except some config file and the nextjs page component. (#314)
=> feat: deprecate default export

docs/start-here/faq.mdx, docs/start-here/roadmap.mdx
Because
- we need to keep our docs up-to-date
This commit
- fix typos
=> docs(start-here): fix typos

src/pages/career/[slug].tsx
Career's path are not correctly rendering, this commit makes next.js server-render our page on demand.
=> fix: make isr server-rendering on demand

src/components/landing/CaseStudy/CaseStudy.tsx
This commit replaces work-safety case study google icon with IOT icon. (close #353)
=> fix: replace work-safety case study icon

src/components/career/PositionList/PositionList.tsx, src/lib/click-up/careerTransformer.spec.ts, src/lib/click-up/clickUp.ts, src/pages/career/[slug].tsx, src/pages/career/index.tsx, src/types/instill.ts
This commit utilize the nature of ClickUp list task api that it will not return closed task in the list to implement the Career page list.
=> feat: remove status field and utilize clickup inherit statues

src/components/ui/PageHead.tsx
This commit removes trailing slash in canonical link to be consistent across sitemap, url and internal link (close #367)
=> fix: remove trailing slash in canonical link

src/components/ui/PageHead.tsx
The landing page canonical link is not correct after #368, this pr fixes this issue.
=> fix: fix landing page canonical link

src/components/landing/CaseStudy/CaseStudy.tsx, src/components/ui/BlueprintContainer.tsx
Because we want the CaseStudy title to stand out, this commit reduces the contract of the background and the blueprint's grid line.
=> feat: update Blueprint line color and the CaseStudy title

tutorials/vdp-cow-counter.mdx
This PR fixes timestamp typo on vdp-cow-counter tutorial.
=> fix: fix timestamp typo

tailwind.config.js
This PR fix DocsLayout breakpoint issue that make the content container had wider width.
=> fix: fix DocsLayout max breakpoint issue

.github/workflows/check-main-lighthouse-score.yml, .github/workflows/cron-remove-old-artifacts.yml, .github/workflows/deploy-prod.yml, .github/workflows/release.yml, .github/workflows/test-and-deploy-staging.yml, .github/workflows/webpack-diff.yml
Because
- We better use the droplet bot token in action
This commit
- Update the token action used to droplet bot token
=> feat: update the token action used

docs/tutorials/build-a-sync-cls-pipeline.mdx
Because
- we need to keep the documentation up to date
This commit
- update the SYNC pipeline response
=> docs(tutorials): update sync pipeline response

docs/core-concepts/ai-task.mdx, docs/prepare-models/overview.mdx
Because
- some links from the Triton server repo are broken
This commit
- update out-of-date links
=> docs(core-concepts,prepare-models): fix broken links

src/components/policy/PolicyPageLayout.tsx, src/components/ui/PageHead.tsx, src/pages/about.tsx, src/pages/blog/[...path].tsx, src/pages/blog/index.tsx, src/pages/career/[slug].tsx, src/pages/career/index.tsx, src/pages/docs/[...path].tsx, src/pages/get-access.tsx, src/pages/index.tsx, src/pages/newsletter.tsx, src/pages/tutorials/[...path].tsx, src/pages/tutorials/index.tsx, src/types/instill.ts
Because
- we want to have richer open graph meta data
This commit
- add `Written by` label, `Category` label, `article:publisher`, `article:published_time`, `article:tag`, `article:modified_time` for blog
- - add `Written by` label, `Use Case` label, `article:publisher`, `article:published_time`, `article:tag`, `article:modified_time` for tutorial
=> feat: add additional open graph tag

docs/core-concepts/ai-task.mdx, docs/import-models/local.mdx
Because
- users can import Text to Image models from locally
This commit
- add how to import the stable diffusion v2.1 from locally
=> docs(import-models,core-concepts): add text to image local model guideline

docs/development/setup-local-development.mdx
Because
- `ITMODE` is by default set to `false` and we now need to specifically set it to `true` for local integration test
This commit
- fix the document accordingly
=> docs(development): fix make local dev setup guideline

docs/core-concepts/ai-task.mdx
Because
- we need to keep the documentation up to date
This commit
- update the Stable Diffusion model names
=> docs(core-concepts): fix stable diffusion model names

src/components/docs/RightSidebar.tsx
Because
- #491
This commit
- remove toc when there has no headers
- close #491
=> fix: remove toc when there has no headers

content.config.tsx, docs/core-concepts/ai-task.mdx, docs/deployment/docker-compose.mdx, docs/deployment/kubernetes-using-helm.mdx, docs/deployment/overview.mdx, docs/development/setup-local-development.mdx, docs/start-here/configuration.mdx, docs/start-here/getting-started.mdx, docs/start-here/roadmap.mdx
Because
- we have multiple deployment approaches now and each requires a document to detail
This commit
- add deployment documents
- update roadmap
- fix several typos
=> docs(deployment): add deployment chapter

docs/deployment/kubernetes-using-helm.mdx
Because
- we want to refactor the Kubernetes deployment docs to be clearer
This commit
- refactor Kubernetes deployment documentation
=> docs(deployment): refactor how to install VDP via Helm

docs/deployment/kubernetes-using-helm.mdx
Because
- VDP helm chart can be deployed on Kubernetes, not constrained to local Kubernetes
This commit
- refactor deployment documentation
=> docs: refactor deployment doc

blog/introducing-vdp.mdx, tutorials/vdp-101-2-quickstart.mdx
Because
- vdp supports deploying on Kubernetes now
This commit
- remove `coming soon` in Kubernetes related text
=> chore: update the text since k8s is supported

tutorials/vdp-101-4-how-to-trigger-a-sync-pipeline.mdx
Because
- `pnpm build` will fail since the type and title are missing from the InfoBlock 
This commit
- refactor info block in vdp tutorial
=> docs(tutorial): fix info block in tutorial

docs/start-here/roadmap.mdx
Because
- we want to keep the roadmap up-to-date 
This commit
- update roadmap
=> docs(start-here): update roadmap

tutorials/vdp-101-2-quickstart.mdx, tutorials/vdp-101-4-how-to-trigger-a-sync-pipeline.mdx, tutorials/vdp-101-7-create-trigger-parse-an-async-pipeline.mdx
Because
- we found a few typos need to be addressed in the tutorials
This commit
- Fix the typos
=> docs: fix typos in VDP 101 tutorials

src/components/ui/Footer/Footer.tsx
Because
- we want to provide the artifact of our media kie
This commit
- add media kit on Footer
=> feat: [INS-152] add media kit

src/components/ui/Footer/Footer.tsx
Because
- We have new tos link
This commit
- add tos link in footer
=> feat: [INS-552] add tos link in footer

src/components/ui/CopyRightText.tsx
Because
- copy right text is wrong
This commit
- fix copy right text
=> fix: fix copy right text

next.config.mjs
Because
- we need to redirect user to our external tos page
This commit
- add redirection of tos page
=> feat: [INS-595] add redirection of tos page

docs/start-here/instill-cloud.mdx, src/pages/pricing.tsx
Because
- we want to add pricing button on nav
- we want to explain the benefit of the Open Alpha period
This commit
- add pricing button on nav
- update Instill Cloud page on documentation
- update the Open Alpha link on the pricing page to Instill Cloud page on documentation
=> docs: add pricing button in nav and open alpha in documentation

src/components/landing/Hero/ConsoleCtaButton.tsx, src/components/landing/Hero/GitHubCtaButton.tsx
Because
- The order of CTA button is wrong
This commit
- update landing page hero CTA button
=> feat: [INS-598] update landing page hero CTA button

src/components/ui/PricingPlanLayout.tsx, src/pages/pricing.tsx
Because
- we want to explain more about each user action on pricing
This commit
- add cta description into pricing page
=> feat: [INS-677] add cta description into pricing page

blog/unstructured-data-etl.mdx, blog/why-instill-ai-exists.mdx, docs/instill-cloud/getting-started.mdx, docs/vdp/faq.mdx, src/components/landing/Faq/Faq.tsx
Because
- Instill Cloud is in Open Alpha testing phase, with all features free. We need to update the corresponding information.
This commit
- update the Instill Cloud information
=> docs(blog,docs,product-website): update Instill Cloud plan info

docs/development/setup-local-development.mdx, docs/vdp/configuration.mdx
Because
- we want to keep the docs up-to-date
This commit
- update the configuration env variables
- update the local development example
=> docs(vdp,development): update configuration and local development

src/components/blog/BlogSearch.tsx, src/components/tutorial/TutorialSearch.tsx
Because
- Fuzzy search threshold is too restrict 
This commit
- fix fuzzy search too restrict issue
=> fix(content): fix fuzzy search too restrict issue

src/pages/index.tsx
Because
- airbyte config path file is update in `connector-destination`
This commit
- updated the path in `instill.tech` repo
=> fix: airbyte config path update because build is failing

src/components/ui/Footer/Footer.tsx
Because
- we don't plan to showcase the demo right now
This commit
- remove the demo website from our Footer
=> chore: remove the demo website from our Footer

src/components/landing/NoCodeInterface.tsx
Because
- we plan to demo the pipeline-builder once it is finish
This commit
- change the link to demo with link to console
=> chore: change the link to demo with link to console

docs/vdp/ai-connectors/openai.mdx, docs/vdp/ai-connectors/stability-ai.mdx
Because
- docs for stability ai and open ai don't have actual data examples
This commit
- adds actual data examples for stability ai and open ai
=> chore: update docs

docs/vdp/ai-connectors/openai.mdx
Because
- we want to remove religious reference from docs
This commit
- removes religious reference from docs
=> chore: update prompt

src/pages/docs/[...path].tsx
Because
- update docs path for commit Meta
This commit
- update docs path for commit Meta
=> fix: update docs path for commit Meta

src/styles/docs.css
Because
- In dark mode the search bar placeholder color is visible
This commit
- Fixed https://github.com/instill-ai/community/issues/414
=> fix: In dark mode the search bar placeholder color not visible

src/components/tutorial/TutorialSearch.tsx
Because
- Broken links have been rectified and closes [#397](https://github.com/instill-ai/community/issues/397)
This commit
- Updated the links so that the user is navigated to the right pages
=> Update TutorialSearch Broken Links

.github/DOCS-CONTRIBUTING.md, CONTRIBUTING.md, blog/celebrate-Hacktoberfest-2023.mdx, blog/introducing-vdp.mdx, draft/vdp-101-3-create-your-first-pipeline.mdx, draft/vdp-101-5-how-to-parse-vdp-responses.mdx, draft/vdp-101-6-pipeline-modes.mdx, src/components/hacktoberfest/Hero/Hero.tsx, src/components/landing/CodeShowcase/CodeShowcase.tsx, src/components/landing/Faq/Faq.tsx, src/components/landing/Hero/GitHubCtaButton.tsx, src/components/landing/HowItWorks/HowItWorks.tsx, src/pages/index.tsx, src/pages/pricing.tsx, tutorials/vdp-aigc-web3-stability-ai-numbers-protocol.mdx, tutorials/vdp-streamlit-yolov7.mdx
Because
- we want to keep the outdated links up-to-date
This commit
- fix outdated links in product website, tutorials and blogs
=> chore: update outdated links in product website

src/components/docs/RightSidebar.tsx, src/components/ui/ArticleRightSidebar.tsx, src/components/ui/ContributeLinks.tsx, src/pages/docs/[...path].tsx
Because
- It adds "Give feedback" link on every documentation page that will redirect user to create new issue about documentation
This commit
- closes the first part of the issue https://github.com/instill-ai/community/issues/394
=> Add Feedback link on the Righthandsidebar

src/components/landing/jumbotron/Jumbotron.tsx, src/components/landing/jumbotron/SwiperButtonNext.tsx, src/components/landing/jumbotron/SwiperButtonPrev.tsx
Because
- a button can't be a children of a button, nextjs was breaking with this error and I couldnt work on another issue
This commit
- just replaces a button inside another button with just one button
all is working as it was before
=> fix: remove button inside button

src/components/landing/jumbotron/Llama2Chat.tsx, src/lib/jumbotron-sdk/llava7b.ts
Because
- update jumbotron-visual-understanding card on website since the Model task has been changed
This commit
- update jumbotron-visual-understanding card on website since the Model task has been changed
=> chore: update jumbotron-visual-understanding card on website since the Model task has been changed

blog/vdp-open-beta.mdx
Because
- we want to add how we want to improve the no-code documentation feature for GA
This commit
- add new section
=> docs(blog): add no-code section in GA

docs/v0.10.0-beta/core/concepts/pipeline.en.mdx, docs/v0.10.0-beta/core/concepts/pipeline.zh_CN.mdx, docs/v0.10.0-beta/quickstart.en.mdx, docs/v0.10.0-beta/quickstart.zh_CN.mdx, docs/v0.10.0-beta/sdk/python.en.mdx, docs/v0.10.0-beta/sdk/python.zh_CN.mdx, docs/v0.10.0-beta/vdp/app-connectors/numbers-protocol.en.mdx, docs/v0.10.0-beta/vdp/app-connectors/numbers-protocol.zh_CN.mdx, docs/v0.10.0-beta/vdp/data-connectors/airbyte.en.mdx, docs/v0.10.0-beta/vdp/data-connectors/airbyte.zh_CN.mdx, docs/v0.10.0-beta/vdp/operators/base64.en.mdx, docs/v0.10.0-beta/vdp/operators/base64.zh_CN.mdx, docs/v0.10.0-beta/vdp/operators/json.en.mdx, docs/v0.10.0-beta/vdp/operators/json.zh_CN.mdx, docs/v0.10.0-beta/vdp/operators/rest.en.mdx, docs/v0.10.0-beta/vdp/operators/rest.zh_CN.mdx, docs/v0.10.0-beta/vdp/operators/textextraction.en.mdx, docs/v0.10.0-beta/vdp/operators/textextraction.zh_CN.mdx
Because
- We've updated the pipeline reference syntax in Core v0.10.0-beta. But the website still use old syntax.
This commit
- Update reference syntax in v0.10.0-beta document
=> docs: update reference syntax in v0.10.0-beta document

docs/v0.10.0-beta/sdk/typescript.en.mdx, docs/v0.10.0-beta/sdk/typescript.zh_CN.mdx, docs/v0.4.1-alpha/sdk/typescript.en.mdx, docs/v0.4.1-alpha/sdk/typescript.zh_CN.mdx, docs/v0.5.0-alpha/sdk/typescript.en.mdx, docs/v0.5.0-alpha/sdk/typescript.zh_CN.mdx, docs/v0.6.0-alpha/sdk/typescript.en.mdx, docs/v0.6.0-alpha/sdk/typescript.zh_CN.mdx, docs/v0.8.0-beta/sdk/typescript.en.mdx, docs/v0.8.0-beta/sdk/typescript.zh_CN.mdx, docs/v0.9.0-beta/sdk/typescript.en.mdx, docs/v0.9.0-beta/sdk/typescript.zh_CN.mdx, src/components/landing/HowItWorks/HowItWorks.tsx
Because
- use new namespace from `@instill-ai/typescript-sdk` to `instill-sdk`
This commit
- use new namespace from `@instill-ai/typescript-sdk` to `instill-sdk`
=> docs: namananand/ins 3306 use new namespace from @instill-ai/typescript-sdk to instill-sdk

src/pages/pricing.tsx
Because
- We have typo for our team plan
This commit
- fix pricing plan typo
=> fix: fix pricing plan typo

docs/v0.10.0-beta/core/deployment/docker-compose.en.mdx, docs/v0.10.0-beta/core/deployment/docker-compose.zh_CN.mdx, docs/v0.11.0-beta/core/deployment/docker-compose.en.mdx, docs/v0.11.0-beta/core/deployment/docker-compose.zh_CN.mdx, docs/v0.12.0-beta/core/deployment/docker-compose.en.mdx, docs/v0.12.0-beta/core/deployment/docker-compose.zh_CN.mdx, docs/v0.6.0-alpha/core/deployment/docker-compose.en.mdx, docs/v0.6.0-alpha/core/deployment/docker-compose.zh_CN.mdx, docs/v0.8.0-beta/core/deployment/docker-compose.en.mdx, docs/v0.8.0-beta/core/deployment/docker-compose.zh_CN.mdx, docs/v0.9.0-beta/core/deployment/docker-compose.en.mdx, docs/v0.9.0-beta/core/deployment/docker-compose.zh_CN.mdx
Because
- version number was old for docker component deployment
This commit
- update version number for docker component deployment
=> chore: update version number for docker component deployment

src/styles/docs.css
- removed duplicates styles, for DocSearch-Button class.
=> docs: fix left searchbox alignment for dark & light mode

src/components/tutorial/TutorialPipelineLabel.tsx
Because
- remove remove startConnector -> endConnector from tutorial page
This commit
- remove remove startConnector -> endConnector from tutorial page
=> chore: remove remove startConnector -> endConnector from tutorial page

.github/CODEOWNERS
Because
- the `CODEOWNERS` file is missing in this repo
This commit
- add it and assign @iamnamananand996 and @EiffelFly as the owners
=> ci(github): add CODEOWNERS

docs/v0.10.0-beta/core/deployment.en.mdx, docs/v0.10.0-beta/core/deployment.zh_CN.mdx, docs/v0.11.0-beta/core/deployment.en.mdx, docs/v0.11.0-beta/core/deployment.zh_CN.mdx, docs/v0.12.0-beta/core/deployment.en.mdx, docs/v0.12.0-beta/core/deployment.zh_CN.mdx, docs/v0.4.1-alpha/core/deployment.en.mdx, docs/v0.4.1-alpha/core/deployment.zh_CN.mdx, docs/v0.5.0-alpha/core/deployment.en.mdx, docs/v0.5.0-alpha/core/deployment.zh_CN.mdx, docs/v0.6.0-alpha/core/deployment.en.mdx, docs/v0.6.0-alpha/core/deployment.zh_CN.mdx, docs/v0.8.0-beta/core/deployment.en.mdx, docs/v0.8.0-beta/core/deployment.zh_CN.mdx, docs/v0.9.0-beta/core/deployment.en.mdx, docs/v0.9.0-beta/core/deployment.zh_CN.mdx
Because
- Elasticsearch relies heavily on the Java heap space for storing and processing data. A minimum of 4GB RAM is required to launch the container.
This commit
- change the instruction accordingly.
=> docs(deployment): increase minimal memory requirement

.github/workflows/webpack-diff.yml
Because
- fix webpack-diff wrong pnpm version
This commit
- fix webpack-diff wrong pnpm version
=> fix: fix webpack-diff wrong pnpm version

.github/CODEOWNERS
Because
- add the shepherd @GeorgeWilliamStrong to look over the doc sanity
This commit
- add @GeorgeWilliamStrong in the `CODEOWNERS` file
=> ci(CODEOWNERS): add George

docs/component/generic.en.mdx, docs/component/generic.zh_CN.mdx
Because
- We need to be consistent in formatting
This commit
- Corrects **Generic Component** to **Generic** component
=> docs(vdp): fix formatting convention for component names

content.config.tsx
Because
- there is a typo causing rendering failure
This commit
- fix the typo
=> fix(docs): fix navbar typo

docs/vdp/clone.en.mdx, docs/vdp/clone.zh-CN.mdx
- Updated URL in /docs/vdp/clone.en.mdx to point to correct resource.
- Verified link is now accessible and directs to the intended page.
Refs: INS-4720
Because
- Link was broken
This commit
- Adds the correct link
=> fix: correct broken link in the documentation

docs/core/concepts.en.mdx, docs/core/concepts.zh-CN.mdx, docs/quickstart.en.mdx, docs/quickstart.zh-CN.mdx
- Fixed broken Pipeline link on the Core Concepts page.
- Fixed broken final Instill Model AI Connector link on the Quickstart page.
- Updated terminology to reflect the shift from connectors to components.
Refs: INS-4726, INS-4724
Because
- I had detected a couple of broken links whilst conducting a review of the documentation (review still in progress - see INS-4730)
This commit
- Fixed broken links on Core Concepts and Quickstart pages, and updates terminology.
=> fix(docs): repair broken links and update terminology

src/components/policy/SecurityPageLayout.tsx, src/components/policy/index.ts, src/components/ui/Footer/Footer.tsx, src/pages/privacy.mdx, src/pages/security.mdx
Because
- we want to provide a publicly accessible page outlining our security practices
This commit
- add security page layout  
- add a security page in the footer
=> chore(website): add security page on product website

docs/core/deployment.en.mdx, docs/core/deployment.zh-CN.mdx, docs/core/deployment/cli.en.mdx, docs/core/deployment/cli.zh-CN.mdx, docs/core/deployment/docker-compose.en.mdx, docs/core/deployment/docker-compose.zh-CN.mdx, docs/core/deployment/kubernetes-using-helm.en.mdx, docs/core/deployment/kubernetes-using-helm.zh-CN.mdx, docs/model/prepare.en.mdx, docs/model/prepare.zh-CN.mdx, docs/welcome.en.mdx, docs/welcome.zh-CN.mdx
Because
- to make the projects in the documentation more visually distinguishable, we have assigned emoji to each project as
- ☁️ Instill Cloud
- 🔮 Instill Core
- 💧 Instill VDP
- ⚗️ Instill Model
- 💾 Instill Artifact
- ⚙️ Instill Component
- 📺 Instill Console
- ⌨️ Instill CLI 
- 📦 Instill SDK
This commit
- add missed emoji in the docs
=> docs(doc): apply emoji to instill projects

.github/workflows/test-and-deploy-staging.yml
Because
- deploy on staging, when something merges into the main
This commit
- deploy on staging, when something merges into the main
=> refactor: deploy on staging, when something merge into main

docs/vdp/credit.en.mdx, docs/vdp/credit.zh-CN.mdx
Because
- Instill is releasing credit subscription tiers.
This commit
- Document organization credits and credit subscriptions.
=> feat: document advanced Instill Credit subscription

docs/vdp/introduction.en.mdx, docs/vdp/introduction.zh-CN.mdx
Because
- VDP was incorrectly referred to as Visual Data Pipeline
This commit
- Corrects this
=> docs(vdp): fix VDP acronym

src/pages/pricing.tsx
Because
- the user wants to check the pricing for top-up credits
This commit
- update the pricing page feature list
=> chore(pricing): add top up credit feature

docs/cloud/credit.en.mdx, docs/cloud/credit.zh-CN.mdx
Because
- Credit purchase is marked as an upcoming feature but it will be included in the next release.
This commit
- Updates the documentation about subscription vs purchased Instill Credit.
=> feat: document Instill Credit purchase

docs/quickstart.en.mdx, docs/quickstart.zh-CN.mdx
Because
- Some gifs show out-of-date UI
This commit
- Removes out-of-date gifs from quickstart
=> docs: remove out-of-date gifs from quickstart

docs/cloud/credit.en.mdx, docs/cloud/credit.zh-CN.mdx
Because
- users can use anthropic with instill credit
This commit
- add doc about the transformation between the token and instill credit
=> chore: doc for anthropic token to instill credit

docs/component/operator/document.en.mdx, docs/component/operator/document.zh-CN.mdx
Because
- the document component input is base64 but lack this info in doc
This commit
- add base64 for the input of pdf to markdown
=> chore: update doc
